### ISSUE TITLE
Ores dropping instead of spawning in the wall

### ISSUE THREAD

**Issue by TealNerd** [DevotedMC/HiddenOre#11]
When people are mining they're reporting the ores are spawning as items rather than replacing stone

**Comment by Maxopoly** [comment]
Based CivClassic getting in the HiddenOre Beta testing we missed on CivTemp

**Comment by ProgrammerDan** [comment]
Did you set the flag `transformIfAble: true` on each drop config? If you didn't, then uh yeah, it'll just drop as items.

**Comment by TealNerd** [comment]
Nope, bagi apparently didn't bother to when making the config. Thanks dan!
