### ISSUE TITLE
Feature - Definable Transform Blocks

### ISSUE THREAD

**Issue by redmag3** [DevotedMC/HiddenOre#23]
When a lottery event is hit and the plugin looks for blocks to transform, a section of optional transformable blocks would be helpful.

When making veins, you could chain ore breaks, so that say 0.1 chance on break coal_ore, transform nearby stone, and cobblestone into additional coal_ore.

**Comment by ProgrammerDan** [comment]
This you can actually do right now -- 

https://github.com/DevotedMC/HiddenOre/blob/master/src/main/resources/config.yml#L128

Just define a configuration for COAL_ORE in addition to one for stone, etc. Since the transform is _to_ coal ore, if it transforms some of the coal ore into coal ore, not an issue.

**Comment by redmag3** [comment]
> This you can actually do right now --

>https://github.com/DevotedMC/HiddenOre/blob/master/src/main/resources/config.yml#L128

>Just define a configuration for COAL_ORE in addition to one for stone, etc. Since the transform is to coal ore, if it transforms some of the coal ore into coal ore, not an issue.

But if I have two entires, one for stone to drop coal, and one for coal to drop coal ... if the even triggers off of a coal break it wont replace anything but coal right? What I'm looking for is for the event that triggers off of breaking coal ore, to generate MORE coal ore out of adjacent stone.

This way I could have say the coal % from stone be say 1% and from breaking coal directly be 10%, but both would replace stone on their event ... is this possible? (was looking for a way without it being a direct drop)

**Comment by redmag3** [comment]
nvmd I got it xD

ty man!
