### ISSUE TITLE
Option to disable console input

### ISSUE THREAD

**Issue by Boy0000** [DevotedMC/HiddenOre#39]
Currently the console is flooded with ore information, making it really hard to find stuff in there sometimes
![image](https://user-images.githubusercontent.com/62521371/122060256-b571a800-cded-11eb-8f66-c8625ea2e381.png)

**Comment by ProgrammerDan** [comment]
It looks like you have debug enabled.

Check your config file for a line like this one:

https://github.com/DevotedMC/HiddenOre/blob/master/src/main/resources/config.yml#L4

if one doesn't exist, add it at the top -- `debug: false`.

**Comment by Boy0000** [comment]
![image](https://user-images.githubusercontent.com/62521371/122064707-a42a9a80-cdf1-11eb-925d-bcbe860d3e57.png)

debug is set to false already

**Comment by ProgrammerDan** [comment]
Yeah, just doublechecked the code. Stats output is normal logging for admins to post-fact check on hiddenore's actions. I agree it can get a bit overwhelming esp if your ore spawn rate is generous.

Thanks for the issue/feature request!
